# Generated by Django 5.1.1 on 2024-11-26 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_range', models.CharField(max_length=20)),
                ('total_artists', models.IntegerField()),
                ('total_tracks', models.IntegerField()),
                ('total_albums', models.IntegerField()),
                ('total_locations', models.IntegerField()),
                ('new_artists_count', models.IntegerField()),
                ('listening_time_hours', models.FloatField()),
                ('top_genres', models.JSONField()),
                ('top_artists', models.JSONField()),
                ('top_tracks', models.JSONField()),
                ('top_albums', models.JSONField()),
                ('top_locations', models.JSONField()),
                ('user_profile', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
